### PR TITLE
Configure constraint violation status

### PR DESCRIPTION
**Pull request by comrt**

### CODE REVIEW

**Comment by lwitkowski** [comment]
Dear @comrt , extremely sorry it took me so long to look into it, I'm no longer working with Quarkus on daily basis, and I had relocation recently, lot of things going on.

I'm a bit hesitant with this PR, as it introduces non-standard http status codes (ExtendedStatus), and I have hard time justifying this complexity for potential benefit.

@pazkooda what do you think about this?

**Comment by pazkooda** [comment]
I had the same feelings when I first saw this issue/PR.
Reason for that `422` origin is WebDAV specific extension (as of [relevant RFC 4918 specification](https://www.rfc-editor.org/rfc/rfc4918)).

This extension is solely focused on HTTP part and all "extension" should be omitted in general.

Just to learn recently that in June 2022 there was update to _HTTP Semantics_ to actually include some stuff into general specification - which includes [HTTP 422](https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content).

If you ask my preference though - simplicity and following HTTP standard defaults wins for me.

**Comment by lwitkowski** [comment]
[comrt](https://github.com/comrt) The conclusion is: making the status configurable is nice, introducing non-standard http codes - not so much. Feel free to simplify your implementation accordingly, although I'll close this PR now.

**Comment by comrt** [comment]
Dear @lwitkowski, there is no need to feel sorry. To be honest i also track of my PR.
I get your point to stick to the HTTP Standard and I'm glad to see you've found a solution for my request👍 
Thank you, your good work is really appreciated.

**Pull request closed without merging**
