### PR TITLE
Bump Quarkus from 2.15.2.Final to 3.0.0.Alpha2

### PR DESCRIPTION
**Pull request by lwitkowski**
- [x] Quarkus 3.0.0.Alpha2
- [x] migrate javax -> jakarta
- [x] unit and integration tests green
- [x] CI pipelines updated
- [x] documentation updated
- [x] native tests green (figure out @NativeImageTest -> @QuarkusIntegrationTest)

### CODE REVIEW

**Comment by lwitkowski** [comment]
I think it's ready to be merged into master and released as 3.0.0.Alpha2 into maven central.

**Comment by pazkooda** [comment]
Will try to look at this tomorrow :)

**Review by pazkooda — APPROVED** [review]
No much changes since I last looked at this and it already was OK.
Fine with me going with `Alpha2`.

Good work! 👏

**Comment by lwitkowski** [comment]
@pazkooda FYI: I branched x3.X and removed this PR-merge from master - I realized it was too soon for 3.0 in master, as Quarkus itself is releasing more and more 2.X versions (they've just branched 2.16). Let's keep 3.0 in a branch for now (3.0.0.Alpha2 was released into maven central nevertheless).

**Pull request merged**
